---
title: "PA1_template"
author: "Paula Sichel"
date: "December 16, 2015"
output: html_document
---

Access the zip file from the course website, unzip as .csv file
```{r, echo=TRUE}
temp <- tempfile()
download.file("http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip", 
              temp)
temp <- unz(temp, "activity.csv")
activity <- read.csv(temp)
unlink(temp)
```

Create a historgram of the activity dataset
```{r, echo=TRUE}
activity$date <- as.Date(activity$date)
days <- aggregate(steps ~ date, data=activity, FUN="sum")
hist(days$steps)
```

Calculate the median and mean 
```{r, echo=TRUE}
median(activity$steps, na.rm=TRUE)

# mean calc goes here - TBD!!!

```

Look at the average daily activity patterm
```{r, echo=TRUE}
pattern <- aggregate(steps ~ interval, data=activity, FUN="sum")
plot(pattern$interval, pattern$steps, type="l")
```

Question: which 5-min interval (snip) contains the max number of steps?
```{r, echo=TRUE}

## this is the value when the MAX occurs, need the MAX interval -- TBD!!
max(pattern$steps, na.rm=TRUE)
```

Calculate the total number of missing values
```{r, echo=FALSE}
missing_count <- nrow(subset(activity, is.na(steps)))
print ("this is the number of missing values:")
print(missing_count)
print ("this is this missing percent of the total number of values:")
print(missing_count/17568*100)


# Inputting missing values -- fill N/A with mean value
#steps <- c()
#for (i in 1:nrow(activity)) {
#  if (is.na(activity$steps[i])) {
#    index <- which(pattern$interval == activity$interval[i])
#    steps[i] <- pattern$steps[index]
#  } else {
#    steps[i] <- activity$steps[i]
#  }
#}
#date <- activity$date
#interval <- activity$interval
#filled_data <- activity.frame(steps, date, interval)
#head(filled_data)


```


